// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateUser(arg1:string):Promise<void>;

export function GetAppState():Promise<main.AppState>;

export function GetBranchGroupedVersions(arg1:Array<main.RepoVersionSource>,arg2:Array<string>,arg3:Record<string, string>,arg4:number,arg5:boolean):Promise<Array<main.BranchGroupedResult>>;

export function GetBranchVersions(arg1:string,arg2:Array<string>):Promise<Array<main.BranchVersion>>;

export function GetBranches():Promise<Array<string>>;

export function GetBranchesWithMode(arg1:string):Promise<Array<string>>;

export function GetRepoPath():Promise<string>;

export function GetRepoPreferences(arg1:string):Promise<main.RepoPreferences>;

export function GetSavedRepositories():Promise<Array<main.SavedRepository>>;

export function OpenFolderDialog():Promise<string>;

export function OpenVersionFileDialog():Promise<string>;

export function PreviewVersionPattern(arg1:string,arg2:string,arg3:string):Promise<main.PatternPreview>;

export function PreviewVersionPatternInBranch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.PatternPreview>;

export function RemoveSavedRepository(arg1:string):Promise<void>;

export function SaveRepoPreferences(arg1:string,arg2:main.RepoPreferences):Promise<void>;

export function SetRepoPath(arg1:string):Promise<void>;

export function SwitchUser(arg1:string):Promise<void>;
