// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBranchVersions(arg1:string):Promise<Array<main.BranchVersion>>;

export function GetBranches():Promise<Array<string>>;

export function GetRepoPath():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function SetRepoPath(arg1:string):Promise<void>;
