// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBranchVersions(arg1) {
  return window['go']['main']['App']['GetBranchVersions'](arg1);
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetRepoPath() {
  return window['go']['main']['App']['GetRepoPath']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function SetRepoPath(arg1) {
  return window['go']['main']['App']['SetRepoPath'](arg1);
}
