// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetBranchGroupedVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBranchGroupedVersions'](arg1, arg2, arg3);
}

export function GetBranchVersions(arg1, arg2) {
  return window['go']['main']['App']['GetBranchVersions'](arg1, arg2);
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetRepoPath() {
  return window['go']['main']['App']['GetRepoPath']();
}

export function GetRepoPreferences(arg1) {
  return window['go']['main']['App']['GetRepoPreferences'](arg1);
}

export function GetSavedRepositories() {
  return window['go']['main']['App']['GetSavedRepositories']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenVersionFileDialog() {
  return window['go']['main']['App']['OpenVersionFileDialog']();
}

export function PreviewVersionPattern(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewVersionPattern'](arg1, arg2, arg3);
}

export function PreviewVersionPatternInBranch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewVersionPatternInBranch'](arg1, arg2, arg3, arg4);
}

export function RemoveSavedRepository(arg1) {
  return window['go']['main']['App']['RemoveSavedRepository'](arg1);
}

export function SaveRepoPreferences(arg1, arg2) {
  return window['go']['main']['App']['SaveRepoPreferences'](arg1, arg2);
}

export function SetRepoPath(arg1) {
  return window['go']['main']['App']['SetRepoPath'](arg1);
}

export function SwitchUser(arg1) {
  return window['go']['main']['App']['SwitchUser'](arg1);
}
